name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CARGO_TERM_COLOR: always
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ftelnov/weaver:0.1.0
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        run: make lint
      - name: Test
        run: make test
